-- 03 Filtering Data with WHERE Clause

SELECT * FROM MENUITEMS
WHERE PRICE >= 10;

SELECT * FROM MENUITEMS
WHERE PRICE IN (01,15);

SELECT * FROM MENUITEMS
WHERE PRICE BETWEEN 01 AND 15;

SELECT * FROM user_info
WHERE NAME LIKE "C%";

-- Sorting and Ordering Results
SELECT * FROM MENUITEMS
ORDER BY restaurant_id ASC, PRICE DESC;

SELECT * FROM RIDER_INFO
LIMIT 10;